import type {
  PipelineDuration,
  DeploymentFrequency,
  TestResults,
  TestSuiteFailure,
} from '../schemas/types';

const daysAgo = (n: number): string => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

export const MOCK_PIPELINE_DURATIONS: PipelineDuration[] = [
  { date: daysAgo(29), devDuration: 6, stagingDuration: 12, prodDuration: 18 },
  { date: daysAgo(28), devDuration: 7, stagingDuration: 11, prodDuration: 19 },
  { date: daysAgo(27), devDuration: 5, stagingDuration: 13, prodDuration: 20 },
  { date: daysAgo(26), devDuration: 8, stagingDuration: 14, prodDuration: 22 },
  { date: daysAgo(25), devDuration: 6, stagingDuration: 12, prodDuration: 21 },
  { date: daysAgo(24), devDuration: 9, stagingDuration: 15, prodDuration: 25 },
  { date: daysAgo(23), devDuration: 7, stagingDuration: 13, prodDuration: 23 },
  { date: daysAgo(22), devDuration: 10, stagingDuration: 16, prodDuration: 28 },
  { date: daysAgo(21), devDuration: 8, stagingDuration: 14, prodDuration: 26 },
  { date: daysAgo(20), devDuration: 11, stagingDuration: 18, prodDuration: 30 },
  { date: daysAgo(19), devDuration: 12, stagingDuration: 20, prodDuration: 35 },
  { date: daysAgo(18), devDuration: 14, stagingDuration: 22, prodDuration: 40 },
  { date: daysAgo(17), devDuration: 15, stagingDuration: 24, prodDuration: 42 },
  { date: daysAgo(16), devDuration: 13, stagingDuration: 21, prodDuration: 38 },
  { date: daysAgo(15), devDuration: 10, stagingDuration: 17, prodDuration: 32 },
  { date: daysAgo(14), devDuration: 9, stagingDuration: 15, prodDuration: 28 },
  { date: daysAgo(13), devDuration: 8, stagingDuration: 14, prodDuration: 25 },
  { date: daysAgo(12), devDuration: 7, stagingDuration: 13, prodDuration: 24 },
  { date: daysAgo(11), devDuration: 9, stagingDuration: 16, prodDuration: 27 },
  { date: daysAgo(10), devDuration: 10, stagingDuration: 17, prodDuration: 30 },
  { date: daysAgo(9), devDuration: 11, stagingDuration: 18, prodDuration: 33 },
  { date: daysAgo(8), devDuration: 12, stagingDuration: 19, prodDuration: 35 },
  { date: daysAgo(7), devDuration: 10, stagingDuration: 16, prodDuration: 29 },
  { date: daysAgo(6), devDuration: 8, stagingDuration: 14, prodDuration: 26 },
  { date: daysAgo(5), devDuration: 7, stagingDuration: 12, prodDuration: 22 },
  { date: daysAgo(4), devDuration: 6, stagingDuration: 11, prodDuration: 20 },
  { date: daysAgo(3), devDuration: 5, stagingDuration: 10, prodDuration: 18 },
  { date: daysAgo(2), devDuration: 6, stagingDuration: 11, prodDuration: 19 },
  { date: daysAgo(1), devDuration: 7, stagingDuration: 12, prodDuration: 21 },
  { date: daysAgo(0), devDuration: 8, stagingDuration: 13, prodDuration: 23 },
];

export const MOCK_DEPLOYMENTS: DeploymentFrequency[] = [
  { date: daysAgo(19), devDeployments: 12 },
  { date: daysAgo(18), devDeployments: 18 },
  { date: daysAgo(17), devDeployments: 25 },
  { date: daysAgo(16), devDeployments: 30 },
  { date: daysAgo(15), devDeployments: 28 },
  { date: daysAgo(14), devDeployments: 5 },
  { date: daysAgo(13), devDeployments: 3 },
  { date: daysAgo(12), devDeployments: 22 },
  { date: daysAgo(11), devDeployments: 35 },
  { date: daysAgo(10), devDeployments: 40 },
  { date: daysAgo(9), devDeployments: 38 },
  { date: daysAgo(8), devDeployments: 42 },
  { date: daysAgo(7), devDeployments: 8 },
  { date: daysAgo(6), devDeployments: 4 },
  { date: daysAgo(5), devDeployments: 20 },
  { date: daysAgo(4), devDeployments: 32 },
  { date: daysAgo(3), devDeployments: 45 },
  { date: daysAgo(2), devDeployments: 38 },
  { date: daysAgo(1), devDeployments: 29 },
  { date: daysAgo(0), devDeployments: 15 },
];

export const MOCK_TEST_RESULTS: TestResults[] = [
  { date: daysAgo(19), passed: 450, failed: 5 },
  { date: daysAgo(18), passed: 448, failed: 7 },
  { date: daysAgo(17), passed: 452, failed: 3 },
  { date: daysAgo(16), passed: 445, failed: 10 },
  { date: daysAgo(15), passed: 440, failed: 15 },
  { date: daysAgo(14), passed: 430, failed: 25 },
  { date: daysAgo(13), passed: 410, failed: 45 },
  { date: daysAgo(12), passed: 390, failed: 65 },
  { date: daysAgo(11), passed: 400, failed: 55 },
  { date: daysAgo(10), passed: 420, failed: 35 },
  { date: daysAgo(9), passed: 435, failed: 20 },
  { date: daysAgo(8), passed: 445, failed: 10 },
  { date: daysAgo(7), passed: 448, failed: 7 },
  { date: daysAgo(6), passed: 450, failed: 5 },
  { date: daysAgo(5), passed: 452, failed: 3 },
  { date: daysAgo(4), passed: 449, failed: 6 },
  { date: daysAgo(3), passed: 451, failed: 4 },
  { date: daysAgo(2), passed: 453, failed: 2 },
  { date: daysAgo(1), passed: 450, failed: 5 },
  { date: daysAgo(0), passed: 447, failed: 8 },
];

export const MOCK_TEST_SUITE_FAILURES: TestSuiteFailure[] = [
  { suite: 'Auth', date: daysAgo(6), failures: 0 },
  { suite: 'Checkout', date: daysAgo(6), failures: 3 },
  { suite: 'Profile', date: daysAgo(6), failures: 1 },
  { suite: 'Search', date: daysAgo(6), failures: 5 },
  { suite: 'Settings', date: daysAgo(6), failures: 2 },
  { suite: 'Auth', date: daysAgo(5), failures: 1 },
  { suite: 'Checkout', date: daysAgo(5), failures: 4 },
  { suite: 'Profile', date: daysAgo(5), failures: 0 },
  { suite: 'Search', date: daysAgo(5), failures: 7 },
  { suite: 'Settings', date: daysAgo(5), failures: 1 },
  { suite: 'Auth', date: daysAgo(4), failures: 2 },
  { suite: 'Checkout', date: daysAgo(4), failures: 6 },
  { suite: 'Profile', date: daysAgo(4), failures: 0 },
  { suite: 'Search', date: daysAgo(4), failures: 8 },
  { suite: 'Settings', date: daysAgo(4), failures: 3 },
  { suite: 'Auth', date: daysAgo(3), failures: 0 },
  { suite: 'Checkout', date: daysAgo(3), failures: 2 },
  { suite: 'Profile', date: daysAgo(3), failures: 1 },
  { suite: 'Search', date: daysAgo(3), failures: 9 },
  { suite: 'Settings', date: daysAgo(3), failures: 0 },
  { suite: 'Auth', date: daysAgo(2), failures: 1 },
  { suite: 'Checkout', date: daysAgo(2), failures: 1 },
  { suite: 'Profile', date: daysAgo(2), failures: 3 },
  { suite: 'Search', date: daysAgo(2), failures: 4 },
  { suite: 'Settings', date: daysAgo(2), failures: 2 },
  { suite: 'Auth', date: daysAgo(1), failures: 0 },
  { suite: 'Checkout', date: daysAgo(1), failures: 0 },
  { suite: 'Profile', date: daysAgo(1), failures: 2 },
  { suite: 'Search', date: daysAgo(1), failures: 3 },
  { suite: 'Settings', date: daysAgo(1), failures: 1 },
  { suite: 'Auth', date: daysAgo(0), failures: 0 },
  { suite: 'Checkout', date: daysAgo(0), failures: 1 },
  { suite: 'Profile', date: daysAgo(0), failures: 0 },
  { suite: 'Search', date: daysAgo(0), failures: 2 },
  { suite: 'Settings', date: daysAgo(0), failures: 0 },
];

